fix(packages/cli): package manager bun error
Error caused by #181.

Run bunx solidui-cli@latest add button, error:

ExecaError: Command failed with exit code 1: bun add '' '@kobalte/core'